### ISSUE TITLE
Frontend Webpages

### ISSUE THREAD

**Issue by Yorzaren** [Yorzaren/authentication-system-leak-detection#1]
Creating some basics pages. It will still need to be refined at a later date once the php files are done.
### TODO:
- [x] index.html - contains the login
- [x]  validate.js - validate password before it gets sent to the php via post
- [x]  admin.html - add user, delete user
- [x]  settings.html - personal to the user allows them change password
