### ISSUE TITLE
PHP scripts for website

### ISSUE THREAD

**Issue by Yorzaren** [Yorzaren/authentication-system-leak-detection#3]
### TODO:

- [ ] logout.php
- [ ] login.php - Somehow return the username and store it so it can be used in the website ex) `Welcome, X!`
- [ ] add_account.php - admin access only
- [ ] delete_account.php - admin access only
- [ ] change_password.php - must be logged into an account

For everything excluding logout.php, run another check to cleanse user input if they somehow bypass the frontend javascript input cleanse and checks.
